sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
  - bash install.sh
script:
  - source env.sh && npm run test
notifications:
  slack: devops-training-spb:2TUVBAPNGyv7FulaSuzDbH6O
deploy:
  app: tranquil-taiga-35769
  provider: heroku
  api_key:
   secure: "P3ObOiYAqaKD59Yq4QFnRsLTCj1M2H0n9PNgfyG3Lvt4kGgg8LX87eTJeaOl5PgOCrUtBXv9B3bPpwfxxwawqpbaEE6P9XauEf/+UJdknXAiw8fBi619WGIVa5VMeQKaIqGsVfsieSOSrz+JE4DVoECoDpkdtt4N9CNX0eU+oGcc994LxzBt4axSe1tqKE7GG1FeUbHymPmQVy7pAHWC+SprdPxg26YMDDnT1j6YwF9xS+tu752FIccIdqdru5fSFQ6nQA4OhnbPgUT9WOpH8kzK1DA5Iq1LmKaYoHWTafxKw7Ar0qs5AdROISSTbJCbxgQOkpApGu7g3bfjcJJ6dYZcWlY+5mFWb8qUPtuoNDcfupQM/oWK9b00huLLL8wX6w8Cov8ich4POz6Dh0bG5nKgzaYm/b2mAa6VbpZKDtIoP2IswLI9WjMlNmUTe4t8oSPHJ/Uy8QfX8PmdJ2+xAtSBqzq2zuWu4oZsrlbXDklFdqpwdCZzjl4raokO7ci8A9qVFHrJ/G+Z15HH6CyPj1d66q1GNjmZoNLtkMJzqrDBoIPWXNc0ActwLRggBfM7T7+55+LWT/5/+pCkPwnGrnlZADcJsqaxRFVQOh7Zg3SZgEVy7J0v0QkzOgcUFVj00IiAegQvWiB9af3EmbhJyAY0RDLVNaaysc/LDZQIZlk="
