sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
- bash install.sh
script:
- source env.sh && npm run test
notifications:
  slack: devops-training-spb:2TUVBAPNGyv7FulaSuzDbH6O
deploy:
  tranquil-taiga-35769
  provider: heroku
  api_key:
    secure: Usm6G9WbxlyhZfjFtKe5T4v1DbZG+JxuJtImCcf/HVoHAynWt3swSdVcGCBd6SiSXAe9TaZE7pNlT6w+ZWQfwjsjJkfVyfOaVQYyNk8GnWcmR3OYqbTrY6RsEnm0+sIt1vKXOIXGtVhhHncSjX8awIauVlMLbrkPG7UggELIPJlkTzpFY/y8AtmBU7KJfIsegxDJ96XHw9u0d3/HAz49e0bPmsRx0BeypEgfKRox6EpTb/vJ95E8GOAP58CdwK4HpW15zYAIQ6KKR/HYxipjQUPy8uWHFD+wLW7EJ7lVoHhFUflC08xIwSCYqFVWPKChBskrii9hS3K0VlAR0gkoo6ol5TJpQBXhe1mDPv/F0lLl+u3Hz31fg/TbfMrJif0jm/eYKcbpfy3uhXi+ea3Q77I8H0CASChEqlSZbfSeEj/AHTlAIujppadq9TvnpP+S9ptsU5PqE1Doehb0y2HKqMhmF/Dia+91lr7BQCijQDly1kg4NUDlSxxE1GEQuMNPQs+GBwlnfyIvOFjhgB6Aynoyeyibc7Ll0tvyBHR4VJKg0pmiQV0oi8rGQNkFbu5sefeeT9BicJb72zOJzf1Qo2op6vLk/pyP35i6V0suyCSDgAaaEThI0F/ee2ZwZeKzkLvPJklUJv1qSoOTqk/4tA8vjuWreG2hS4R3HiCTrlk=
